name: format check dockerfile + github actions
on:
  push:
    paths:
      - ".github/workflows/**"
      - Dockerfile
jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v5
      - name: copy .env
        run: cp .env.example .env
      - name: format check dockerfile
        run: make format_check_dockerfile
      - name: format check github actions
        run: make format_check_github_actions
