name: lint dockerfile + github actions
on:
  push:
    paths:
      - ".github/workflows/**"
      - Dockerfile
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v5
      - name: copy .env
        run: cp .env.example .env
      - name: lint dockerfile
        run: make lint_dockerfile
      - name: lint github actions
        run: make lint_github_actions
