name: lint-dockerfile

on:
  push:

jobs:
  lint-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v5
      - name: copy .env
        run: cp .env.example .env
      - name: lint-dockerfile
        run: make lint_dockerfile
